package com.school.management.School.service;

import java.io.ByteArrayOutputStream;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Table;
import com.lowagie.text.pdf.PdfWriter;
import com.school.management.School.entity.FeePayment;
import com.school.management.School.entity.Student;
import com.school.management.School.entity.StudentFees;
import com.school.management.School.repository.FeePaymentRepository;
import com.school.management.School.repository.StudentFeesRepository;
import com.school.management.School.repository.StudentRepository;

@Service
public class ReceiptPdfService {

	@Autowired
	private FeePaymentRepository feePaymentRepository;

	@Autowired
	private StudentFeesRepository studentFeesRepository;

	@Autowired
	private StudentRepository studentRepository;

	public byte[] generateReceipt(Long schoolId, Long studentId, Long studentFeeId) {

		try {

			// =========================
			// FETCH STUDENT
			// =========================

			Student student = studentRepository.findById(studentId)
					.orElseThrow(() -> new RuntimeException("Student not found"));

			// =========================
			// FETCH STUDENT FEES
			// =========================

			StudentFees studentFees = studentFeesRepository.findById(studentFeeId)
					.orElseThrow(() -> new RuntimeException("Student fee not found"));

			// =========================
			// FETCH PAYMENT HISTORY
			// =========================

			List<FeePayment> payments = feePaymentRepository.findBySchoolIdAndStudentFeeId(schoolId, studentFeeId);

			// =========================
			// CREATE PDF
			// =========================

			ByteArrayOutputStream out = new ByteArrayOutputStream();

			Document document = new Document();

			PdfWriter.getInstance(document, out);

			document.open();

			// =========================
			// FONT
			// =========================

			Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 20);

			Font normalFont = FontFactory.getFont(FontFactory.HELVETICA, 12);

			// =========================
			// TITLE
			// =========================

			Paragraph title = new Paragraph("FEE RECEIPT", titleFont);

			document.add(title);

			document.add(new Paragraph(" "));

			// =========================
			// STUDENT DETAILS
			// =========================

			document.add(new Paragraph("Student Name : " + student.getFullName(), normalFont));

			document.add(new Paragraph("Father Name : " + student.getParentName(), normalFont));

			document.add(new Paragraph("Mobile Number : " + student.getParentMobile(), normalFont));

			document.add(new Paragraph("Class : " + studentFees.getClassName(), normalFont));

			document.add(new Paragraph("Section : " + studentFees.getSection(), normalFont));

			document.add(new Paragraph("Academic Year : " + studentFees.getAcademicYear(), normalFont));

			document.add(new Paragraph("-------------------------------------"));

			// =========================
			// FEE SUMMARY
			// =========================

			document.add(new Paragraph("Total Amount : ₹ " + studentFees.getTotalAmount(), normalFont));

			document.add(new Paragraph("Paid Amount : ₹ " + studentFees.getPaidAmount(), normalFont));

			document.add(new Paragraph("Due Amount : ₹ " + studentFees.getDueAmount(), normalFont));

			document.add(new Paragraph(" "));

			// =========================
			// PAYMENT HISTORY TITLE
			// =========================

			Paragraph paymentTitle = new Paragraph("Payment History", titleFont);

			document.add(paymentTitle);

			document.add(new Paragraph(" "));

			// =========================
			// TABLE
			// =========================

			Table table = new Table(5);

			table.addCell("Receipt No");
			table.addCell("Date");
			table.addCell("Amount");
			table.addCell("Mode");
			table.addCell("Remarks");

			for (FeePayment payment : payments) {

				table.addCell(payment.getReceiptNumber() != null ? payment.getReceiptNumber() : "-");

				table.addCell(payment.getPaymentDate() != null ? payment.getPaymentDate().toString() : "-");

				table.addCell("₹ " + payment.getAmountPaid());

				table.addCell(payment.getPaymentMode() != null ? payment.getPaymentMode() : "-");

				table.addCell(payment.getRemarks() != null ? payment.getRemarks() : "-");
			}

			document.add(table);

			document.add(new Paragraph(" "));

			document.add(new Paragraph("Generated By School Management System", normalFont));

			// =========================
			// CLOSE
			// =========================

			document.close();

			return out.toByteArray();

		} catch (Exception e) {

			throw new RuntimeException("Error generating receipt PDF", e);
		}
	}

}
